var searchData=
[
  ['x_0',['x',['../md_vendor_2guzzlehttp_2guzzle_2_u_p_g_r_a_d_i_n_g.html#autotoc_md510',1,'2.8 to 3.x'],['../md_vendor_2laravel_2framework_2_c_h_a_n_g_e_l_o_g.html',1,'Release Notes for 11.x']]],
  ['x_20to_204_200_1',['3.x to 4.0',['../md_vendor_2guzzlehttp_2guzzle_2_u_p_g_r_a_d_i_n_g.html#autotoc_md460',1,'']]],
  ['x_20to_205_200_2',['4.x to 5.0',['../md_vendor_2guzzlehttp_2guzzle_2_u_p_g_r_a_d_i_n_g.html#autotoc_md453',1,'']]],
  ['x_20unreleased_20a_3',['&lt;a href=&quot;https://github.com/laravel/framework/compare/v11.43.1...11.x&quot; &gt;Unreleased&lt;/a&gt;',['../md_vendor_2laravel_2framework_2_c_h_a_n_g_e_l_o_g.html#autotoc_md802',1,'']]],
  ['xcallable_4',['Xcallable',['../class_psy_1_1_readline_1_1_hoa_1_1_xcallable.html',1,'Psy::Readline::Hoa']]],
  ['xdebugdriver_5',['XdebugDriver',['../class_sebastian_bergmann_1_1_code_coverage_1_1_driver_1_1_xdebug_driver.html',1,'SebastianBergmann::CodeCoverage::Driver']]],
  ['xdebugnotavailableexception_6',['XdebugNotAvailableException',['../class_sebastian_bergmann_1_1_code_coverage_1_1_driver_1_1_xdebug_not_available_exception.html',1,'SebastianBergmann::CodeCoverage::Driver']]],
  ['xdebugnotenabledexception_7',['XdebugNotEnabledException',['../class_sebastian_bergmann_1_1_code_coverage_1_1_driver_1_1_xdebug_not_enabled_exception.html',1,'SebastianBergmann::CodeCoverage::Driver']]],
  ['xlifffiledumper_8',['XliffFileDumper',['../class_symfony_1_1_component_1_1_translation_1_1_dumper_1_1_xliff_file_dumper.html',1,'Symfony::Component::Translation::Dumper']]],
  ['xlifffileloader_9',['XliffFileLoader',['../class_symfony_1_1_component_1_1_translation_1_1_loader_1_1_xliff_file_loader.html',1,'Symfony::Component::Translation::Loader']]],
  ['xlifflintcommand_10',['XliffLintCommand',['../class_symfony_1_1_component_1_1_translation_1_1_command_1_1_xliff_lint_command.html',1,'Symfony::Component::Translation::Command']]],
  ['xliffutils_11',['XliffUtils',['../class_symfony_1_1_component_1_1_translation_1_1_util_1_1_xliff_utils.html',1,'Symfony::Component::Translation::Util']]],
  ['xml_12',['XML',['../C:/Users/tomys/gestion_stock/vendor/hamcrest/hamcrest-php/README.md#autotoc_md800',1,'']]],
  ['xml_13',['Xml',['../class_league_1_1_common_mark_1_1_util_1_1_xml.html',1,'League\CommonMark\Util\Xml'],['../class_p_h_p_unit_1_1_text_u_i_1_1_xml_configuration_1_1_code_coverage_1_1_report_1_1_xml.html',1,'PHPUnit\TextUI\XmlConfiguration\CodeCoverage\Report\Xml'],['../class_p_h_p_unit_1_1_util_1_1_xml.html',1,'PHPUnit\Util\Xml']]],
  ['xml_14',['xml',['../class_p_h_p_unit_1_1_text_u_i_1_1_xml_configuration_1_1_code_coverage_1_1_code_coverage.html#a21e50a2d6c025f076dd24fd5763aefde',1,'PHPUnit::TextUI::XmlConfiguration::CodeCoverage::CodeCoverage']]],
  ['xml_20service_20descriptions_20to_20json_15',['Convert XML Service Descriptions to JSON',['../md_vendor_2guzzlehttp_2guzzle_2_u_p_g_r_a_d_i_n_g.html#autotoc_md512',1,'']]],
  ['xml_20tt_16',['Read from &lt;tt&gt;manifest.xml&lt;/tt&gt;',['../C:/Users/tomys/gestion_stock/vendor/phar-io/manifest/README.md#autotoc_md1348',1,'']]],
  ['xmlconfigurationfilefinder_17',['XmlConfigurationFileFinder',['../class_p_h_p_unit_1_1_text_u_i_1_1_cli_arguments_1_1_xml_configuration_file_finder.html',1,'PHPUnit::TextUI::CliArguments']]],
  ['xmldescriptor_18',['XmlDescriptor',['../class_symfony_1_1_component_1_1_console_1_1_descriptor_1_1_xml_descriptor.html',1,'Symfony::Component::Console::Descriptor']]],
  ['xmlexception_19',['XmlException',['../class_p_h_p_unit_1_1_util_1_1_xml_1_1_xml_exception.html',1,'PHPUnit\Util\Xml\XmlException'],['../class_sebastian_bergmann_1_1_code_coverage_1_1_xml_exception.html',1,'SebastianBergmann\CodeCoverage\XmlException']]],
  ['xmlfileloader_20',['XmlFileLoader',['../class_symfony_1_1_component_1_1_routing_1_1_loader_1_1_xml_file_loader.html',1,'Symfony::Component::Routing::Loader']]],
  ['xmlnoderendererinterface_21',['XmlNodeRendererInterface',['../interface_league_1_1_common_mark_1_1_xml_1_1_xml_node_renderer_interface.html',1,'League::CommonMark::Xml']]],
  ['xmlreadercaster_22',['XmlReaderCaster',['../class_symfony_1_1_component_1_1_var_dumper_1_1_caster_1_1_xml_reader_caster.html',1,'Symfony::Component::VarDumper::Caster']]],
  ['xmlrenderer_23',['XmlRenderer',['../class_league_1_1_common_mark_1_1_xml_1_1_xml_renderer.html',1,'League::CommonMark::Xml']]],
  ['xmlresourcecaster_24',['XmlResourceCaster',['../class_symfony_1_1_component_1_1_var_dumper_1_1_caster_1_1_xml_resource_caster.html',1,'Symfony::Component::VarDumper::Caster']]],
  ['xmlresponsehandler_25',['XmlResponseHandler',['../class_whoops_1_1_handler_1_1_xml_response_handler.html',1,'Whoops::Handler']]],
  ['xmlserializer_26',['XMLSerializer',['../class_the_seer_1_1_tokenizer_1_1_x_m_l_serializer.html',1,'TheSeer::Tokenizer']]],
  ['xoauth2authenticator_27',['XOAuth2Authenticator',['../class_symfony_1_1_component_1_1_mailer_1_1_transport_1_1_smtp_1_1_auth_1_1_x_o_auth2_authenticator.html',1,'Symfony::Component::Mailer::Transport::Smtp::Auth']]],
  ['xor_28',['xor',['../class_brick_1_1_math_1_1_big_integer.html#ae2cba67d26b1f9418fd8e2cad3874eee',1,'Brick\Math\BigInteger\xor()'],['../class_brick_1_1_math_1_1_internal_1_1_calculator.html#a1118ed43eb1dad7306400712a3456bed',1,'Brick\Math\Internal\Calculator\xor()'],['../class_brick_1_1_math_1_1_internal_1_1_calculator_1_1_gmp_calculator.html#a8b2a47282e9f04430e74d8dfe4cdba74',1,'Brick\Math\Internal\Calculator\GmpCalculator\xor()']]],
  ['xpathexpr_29',['XPathExpr',['../class_symfony_1_1_component_1_1_css_selector_1_1_x_path_1_1_x_path_expr.html',1,'Symfony::Component::CssSelector::XPath']]],
  ['xx_30',['0.9.4 (XXXX-XX-XX)',['../md_vendor_2mockery_2mockery_2_c_h_a_n_g_e_l_o_g.html#autotoc_md1141',1,'']]],
  ['xx_20xx_31',['0.9.4 (XXXX-XX-XX)',['../md_vendor_2mockery_2mockery_2_c_h_a_n_g_e_l_o_g.html#autotoc_md1141',1,'']]],
  ['xxxx_20xx_20xx_32',['0.9.4 (XXXX-XX-XX)',['../md_vendor_2mockery_2mockery_2_c_h_a_n_g_e_l_o_g.html#autotoc_md1141',1,'']]]
];
