var class_p_h_p_unit_1_1_text_u_i_1_1_xml_configuration_1_1_replace_restrict_deprecations_with_ignore_deprecations =
[
    [ "migrate", "class_p_h_p_unit_1_1_text_u_i_1_1_xml_configuration_1_1_replace_restrict_deprecations_with_ignore_deprecations.html#ad6a06a077dac05fbcd0076625daadd5f", null ]
];