var namespace_mockery_1_1_generator_1_1_string_manipulation_1_1_pass =
[
    [ "AvoidMethodClashPass", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_avoid_method_clash_pass.html", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_avoid_method_clash_pass" ],
    [ "CallTypeHintPass", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_call_type_hint_pass.html", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_call_type_hint_pass" ],
    [ "ClassAttributesPass", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_class_attributes_pass.html", null ],
    [ "ClassNamePass", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_class_name_pass.html", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_class_name_pass" ],
    [ "ClassPass", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_class_pass.html", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_class_pass" ],
    [ "ConstantsPass", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_constants_pass.html", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_constants_pass" ],
    [ "InstanceMockPass", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_instance_mock_pass.html", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_instance_mock_pass" ],
    [ "InterfacePass", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_interface_pass.html", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_interface_pass" ],
    [ "MagicMethodTypeHintsPass", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_magic_method_type_hints_pass.html", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_magic_method_type_hints_pass" ],
    [ "MethodDefinitionPass", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_method_definition_pass.html", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_method_definition_pass" ],
    [ "Pass", "interface_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_pass.html", "interface_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_pass" ],
    [ "RemoveBuiltinMethodsThatAreFinalPass", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_remove_builtin_methods_that_are_final_pass.html", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_remove_builtin_methods_that_are_final_pass" ],
    [ "RemoveDestructorPass", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_remove_destructor_pass.html", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_remove_destructor_pass" ],
    [ "RemoveUnserializeForInternalSerializableClassesPass", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_remove_unserialize_for_internal_serializable_classes_pass.html", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_remove_unserialize_for_internal_serializable_classes_pass" ],
    [ "TraitPass", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_trait_pass.html", "class_mockery_1_1_generator_1_1_string_manipulation_1_1_pass_1_1_trait_pass" ]
];