var namespace_carbon_1_1_exceptions =
[
    [ "BadComparisonUnitException", "class_carbon_1_1_exceptions_1_1_bad_comparison_unit_exception.html", "class_carbon_1_1_exceptions_1_1_bad_comparison_unit_exception" ],
    [ "BadFluentConstructorException", "class_carbon_1_1_exceptions_1_1_bad_fluent_constructor_exception.html", "class_carbon_1_1_exceptions_1_1_bad_fluent_constructor_exception" ],
    [ "BadFluentSetterException", "class_carbon_1_1_exceptions_1_1_bad_fluent_setter_exception.html", "class_carbon_1_1_exceptions_1_1_bad_fluent_setter_exception" ],
    [ "BadMethodCallException", "interface_carbon_1_1_exceptions_1_1_bad_method_call_exception.html", null ],
    [ "EndLessPeriodException", "class_carbon_1_1_exceptions_1_1_end_less_period_exception.html", null ],
    [ "Exception", "interface_carbon_1_1_exceptions_1_1_exception.html", null ],
    [ "ImmutableException", "class_carbon_1_1_exceptions_1_1_immutable_exception.html", "class_carbon_1_1_exceptions_1_1_immutable_exception" ],
    [ "InvalidArgumentException", "interface_carbon_1_1_exceptions_1_1_invalid_argument_exception.html", null ],
    [ "InvalidCastException", "class_carbon_1_1_exceptions_1_1_invalid_cast_exception.html", null ],
    [ "InvalidDateException", "class_carbon_1_1_exceptions_1_1_invalid_date_exception.html", "class_carbon_1_1_exceptions_1_1_invalid_date_exception" ],
    [ "InvalidFormatException", "class_carbon_1_1_exceptions_1_1_invalid_format_exception.html", null ],
    [ "InvalidIntervalException", "class_carbon_1_1_exceptions_1_1_invalid_interval_exception.html", null ],
    [ "InvalidPeriodDateException", "class_carbon_1_1_exceptions_1_1_invalid_period_date_exception.html", null ],
    [ "InvalidPeriodParameterException", "class_carbon_1_1_exceptions_1_1_invalid_period_parameter_exception.html", null ],
    [ "InvalidTimeZoneException", "class_carbon_1_1_exceptions_1_1_invalid_time_zone_exception.html", null ],
    [ "InvalidTypeException", "class_carbon_1_1_exceptions_1_1_invalid_type_exception.html", null ],
    [ "NotACarbonClassException", "class_carbon_1_1_exceptions_1_1_not_a_carbon_class_exception.html", "class_carbon_1_1_exceptions_1_1_not_a_carbon_class_exception" ],
    [ "NotAPeriodException", "class_carbon_1_1_exceptions_1_1_not_a_period_exception.html", null ],
    [ "NotLocaleAwareException", "class_carbon_1_1_exceptions_1_1_not_locale_aware_exception.html", "class_carbon_1_1_exceptions_1_1_not_locale_aware_exception" ],
    [ "OutOfRangeException", "class_carbon_1_1_exceptions_1_1_out_of_range_exception.html", "class_carbon_1_1_exceptions_1_1_out_of_range_exception" ],
    [ "ParseErrorException", "class_carbon_1_1_exceptions_1_1_parse_error_exception.html", "class_carbon_1_1_exceptions_1_1_parse_error_exception" ],
    [ "RuntimeException", "interface_carbon_1_1_exceptions_1_1_runtime_exception.html", null ],
    [ "UnitException", "class_carbon_1_1_exceptions_1_1_unit_exception.html", null ],
    [ "UnitNotConfiguredException", "class_carbon_1_1_exceptions_1_1_unit_not_configured_exception.html", "class_carbon_1_1_exceptions_1_1_unit_not_configured_exception" ],
    [ "UnknownGetterException", "class_carbon_1_1_exceptions_1_1_unknown_getter_exception.html", "class_carbon_1_1_exceptions_1_1_unknown_getter_exception" ],
    [ "UnknownMethodException", "class_carbon_1_1_exceptions_1_1_unknown_method_exception.html", "class_carbon_1_1_exceptions_1_1_unknown_method_exception" ],
    [ "UnknownSetterException", "class_carbon_1_1_exceptions_1_1_unknown_setter_exception.html", "class_carbon_1_1_exceptions_1_1_unknown_setter_exception" ],
    [ "UnknownUnitException", "class_carbon_1_1_exceptions_1_1_unknown_unit_exception.html", "class_carbon_1_1_exceptions_1_1_unknown_unit_exception" ],
    [ "UnreachableException", "class_carbon_1_1_exceptions_1_1_unreachable_exception.html", null ],
    [ "UnsupportedUnitException", "class_carbon_1_1_exceptions_1_1_unsupported_unit_exception.html", null ]
];